#vamos ver um pouco sobre Numpy

#####a biblioteca numpy é usada na análise de dados por conta de seu tempo de processamento em comparação com as listas

In [ ]:
import numpy as np

#o que é um array?

#####um array é um conjunto de dados (tipo uma lista)

#####existem alguns tipos de arrays, sendo eles: vertor (com apenas uma dimensão), matriz (com duas dimensões) e o tensor (com três os mais dimensões)

#vamos criar um array agora

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

print(type(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


#trabalhando com np.zeros()

#####para trabalharmos com arrays onde todos os valores sejam zeros

In [11]:
zero_array = np.zeros(shape=(5, 3, 6))
print(zero_array)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


#usando o np.ones()

#####para trabalharmos com arrays onde todos os valores sejam um

In [15]:
um_array = np.ones(5)
print(um_array)

[1. 1. 1. 1. 1.]


#usando o np.empty()

#####ele não deixa nenhum valor ser vazio, por isso entrega vários números aleatórios

In [19]:
b = np.empty(shape=(2, 3))
print(b)

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]


#usando o np.arange()

#####trabalha, por exemplo, com listas de números decorrentes, tipo, quero uma contagem de 10 números de 0 à 10 (não precisa definir valor inicial) e, se quiser começar por outro valor da também, só definir o valor inicial juntamente com o ponto de parada, obs: também é possível configurar o pulo (steep)



In [28]:
c = np.arange(10)
print(c)

d = np.arange(5, 50, 5)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[]


#usando o np.linspace()

#####é um array com uma sequência linear, baseando-se na equação da reta

In [33]:
e = np.linspace(0, 100, num=10, endpoint=False)
print(e)

[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]


#vendo o tamanho do array

#####lembrando que é possível pegar tanto tamanho da dimensão do array quanto a quantidade de itens

In [34]:
zero_array = np.zeros(shape=(5, 3, 6))
print(zero_array)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [37]:
print(zero_array.shape) #pegando o tamanho do array
print(zero_array.size) #quantidade de itens
print(zero_array.ndim) #quantidade de dimensões/'linhas'

(5, 3, 6)
90
3


#transformando um vetor em uma matrix

#####transformando um array de uma dimensão em um array com duas dimensões

In [42]:
vetor_a = np.array([1, 2, 3])
print(vetor_a.shape)
print(vetor_a.ndim)
print(vetor_a)

(3,)
1
[1 2 3]


In [44]:
vetor_a_dois = vetor_a[np.newaxis,:]
print(vetor_a_dois.shape)
print(vetor_a_dois.ndim)
print(vetor_a_dois)

(1, 3)
2
[[1 2 3]]


In [45]:
vetor_a_dois_um = vetor_a[:,np.newaxis]
print(vetor_a_dois_um.shape)
print(vetor_a_dois_um.ndim)
print(vetor_a_dois_um)

(3, 1)
2
[[1]
 [2]
 [3]]


#pegando um dados específico do array

In [48]:
print(vetor_a_dois_um[2][0])

3


#concatenação de array

#####vamos unir dois arrays

In [50]:
arr_um = np.array([1, 2, 3])
arr_dois = np.array([4, 5, 6])

arr_geral_um = np.concatenate([arr_um, arr_dois])
arr_geral_dois = np.concatenate([arr_dois, arr_um])

print(arr_geral_um)
print(arr_geral_dois)

[1 2 3 4 5 6]
[4 5 6 1 2 3]


#consultando itens de um array

#####isso já foi feito, mas agora em vez de passar o caminho do item que queremos vamos passar uma regra, dai os itens que obedecerem a essa regra serão exibidos

In [63]:
arr_a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

maior = arr_a[arr_a >= 5]
print(maior)

par = arr_a[arr_a%2 != 0]
print(par)

[ 5  6  7  8  9 10 11 12]
[ 1  3  5  7  9 11]


#operações com arrays

#####é possível realizar diversas operações com arrays, como: soma, valor mínimo, valor, máximo, média, entre outros

In [67]:
arr_soma = np.array([1, 2, 3])

print(arr_soma.sum()) #soma
print(arr_soma.min()) #menor valor
print(arr_soma.max()) #maior valor
print(arr_soma.mean()) #media

6
1
3
2.0


#gerando números aleatórios

In [68]:
from numpy.random import default_rng

In [72]:
rng = default_rng()
aleatorio = rng.integers(30, size=(3, 6))
print(aleatorio)

[[ 0 18 18  2 13  4]
 [29 25 18  5 29  9]
 [26  9  7 12 12 19]]


#diferença entre arrays e listas

1.   ao colocar uma lista e um array com números e strings, o array irá transformar todos os elementos em string, assim aumentando a velocidade de processamento; enquanto a lista mantém os valores inteiros como inteiros e as strings como strings. em resumo, o array não permite que exista tipos de dados diferentes dentro dele
2.   outra diferença interessante, é que um array não exibi vírgulas enquanto a lista sim
3.  a lista não permite realizar operações matetmaticas, exemplo, multiplicação, entre listas



In [76]:
arr_test = np.array([1, 'mariana', 3, 4, 5, 6, 7, 8])
print(arr_test)
print(type(arr_test))

print("--------------------------")
list_test = [1, 'mariana', 3, 4, 5, 6, 7, 8]
print(list_test)
print(type(list_test))

['1' 'mariana' '3' '4' '5' '6' '7' '8']
<class 'numpy.ndarray'>
--------------------------
[1, 'mariana', 3, 4, 5, 6, 7, 8]
<class 'list'>


#fazendo um teste de processamento

In [77]:
from time import process_time

In [84]:
list_a = list(rng.integers(10, 100, size=1000000))
list_b = list(rng.integers(10, 100, size=1000000))

In [81]:
c = []

t1 = process_time()
for i in range(len(list_a)):
  c.append(list_a[i] * list_b[i])

t2 = process_time()

print(t2-t1)

0.5158022220000049


In [83]:
arr_a = rng.integers(10, 100, size=1000000)
arr_b = rng.integers(10, 100, size=1000000)

t1 = process_time()
calc = arr_a * arr_b
t2 = process_time()

print(t2-t1)

0.009740612000001647
